/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form_perpustakaan;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import perpustakaan.Anggota;
import perpustakaan.Buku;
import perpustakaan.Peminjaman;
import perpustakaan.Perpustakaan;

/**
 *
 * @author ACER
 */
public class FormPeminjaman extends javax.swing.JFrame {

    private Perpustakaan perpus;
    private ArrayList<Anggota> user = new ArrayList<>();
    private ArrayList<Buku> dataBuku = new ArrayList<>();

    /**
     * Creates new form FormPeminjaman
     */
    private List<String> bacaBukuDariFile(String fileName) {
        List<String> daftarBuku = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Asumsikan setiap baris adalah judul buku
                String[] dataBuku = line.split(","); // Pisahkan berdasarkan koma
                if (dataBuku.length > 0) {
                    daftarBuku.add(dataBuku[0]); // Menambahkan judul buku ke daftar
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return daftarBuku;
    }

// Di dalam metode inisialisasi atau constructor Anda
    public void inisialisasiComboBox() {
        List<String> bukuList = bacaBukuDariFile("buku.txt");
        for (String buku : bukuList) {
            cbBuku.addItem(buku); // Mengisi ComboBox dengan daftar buku
        }
    }
    
    private ArrayList<Buku> loadBukuFromFile(String filePath) {
        ArrayList<Buku> bukuList = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("\\,"); // Memisahkan berdasarkan pemisah '|'
                if (parts.length == 5) {
//                    int id = Integer.parseInt(parts[0]);
                    String judul = parts[0];
                    String pengarang = parts[1];
                    String isbn = parts[2];
                    int tahunTerbit = Integer.parseInt(parts[3]);
                    boolean tersedia = Boolean.parseBoolean(parts[4]);
                    bukuList.add(new Buku(judul, pengarang, isbn, tahunTerbit, tersedia));
                    System.out.println("Buku dimuat: " + judul);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return bukuList;
    }
    

    public FormPeminjaman(ArrayList<Anggota> user) {
        initComponents();
        this.user = user;
        this.perpus = Perpustakaan.getInstance();
        this.dataBuku = loadBukuFromFile("buku.txt");
        inisialisasiComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbBuku = new javax.swing.JComboBox<>();
        tfNamaAnggota = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 73, 122));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form_perpustakaan/assets/PENS_polos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Politeknik Elektronika Negeri Surabaya");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PERPUSTAKAAN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 225));

        jLabel6.setText("Pilih Buku");

        jLabel7.setText("Nama Anggota");

        cbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cbBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBukuActionPerformed(evt);
            }
        });

        tfNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaAnggotaActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btnSubmit.setPreferredSize(new java.awt.Dimension(72, 20));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tfNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnBack)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaAnggotaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        // Ambil data anggota dan buku
        String nmAnggota = tfNamaAnggota.getText();
        String bukuDipilih = (String) cbBuku.getSelectedItem(); // Casting untuk mendapatkan objek Buku

        // Misalkan tanggal peminjaman adalah hari ini dan tanggal kembali 7 hari ke depan
        String tanggalPinjam = LocalDate.now().toString(); // Menggunakan LocalDate untuk mendapatkan tanggal saat ini
        String tanggalKembali = LocalDate.now().plusDays(7).toString(); // Menambahkan 7 hari

        if (bukuDipilih != null && nmAnggota != null && !nmAnggota.isEmpty()) {
            // Cari anggota berdasarkan nama
            Anggota anggota = perpus.cariAnggota(nmAnggota);
//            System.out.println("Nama Anggota: " + nmAnggota);

            if (anggota != null) {
                Buku buku = perpus.cariBuku(bukuDipilih);
                System.out.println("Buku Dipilih: " + buku);
                if (buku == null) {
                    JOptionPane.showMessageDialog(this, "Buku tidak ditemukan!");
                } else {
                    Peminjaman peminjaman = new Peminjaman(buku, anggota, tanggalPinjam, tanggalKembali);
                    perpus.tambahPeminjaman(peminjaman); // Simpan peminjaman ke Perpustakaan
                    perpus.simpanPeminjamanKeFile();
                    JOptionPane.showMessageDialog(this, "Buku berhasil dipinjam!");
                    // Opsional: Bersihkan input setelah peminjaman
                    tfNamaAnggota.setText("");
                    cbBuku.setSelectedIndex(-1); // Reset combo box
                }
            } else {
                JOptionPane.showMessageDialog(this, "Anggota tidak ditemukan!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data anggota atau buku tidak valid!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FormMenu f1 = new FormMenu(this.user);
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBukuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPeminjaman(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfNamaAnggota;
    // End of variables declaration//GEN-END:variables
}
